---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: murray-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: murray-storage
  local:
    path: /storage/murraydata
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jamovi4jonathon
---
apiVersion: v1
kind: Service
metadata:
  labels:
  name: murrayserver
spec:
  selector:
    app: murrayserver
  ports:
    - name: server
      port: 8080
      protocol: TCP
    - name: data
      port: 80
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: murrayserver-pvc
spec:
  storageClassName: murray-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: murrayserver
  labels:
    app: murrayserver
spec:
  selector:
    matchLabels:
      app: murrayserver
  template:
    metadata:
      labels:
        app: murrayserver
    spec:
      containers:
        - name: murrayserver
          image: murrayserver
          imagePullPolicy: Never
          env:
            - name: MURRAYSERVER_LOG_PATH
              value: /data
          volumeMounts:
            - mountPath: "/data"
              name: storage
          resources:
            requests:
              cpu: "100m"
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: "/usr/share/nginx/html/data"
              name: storage
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          resources:
            requests:
              cpu: "100m"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: murrayserver-pvc
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
      server {
          listen       80;
          listen  [::]:80;
          server_name  localhost;

          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
              autoindex on;
          }
      }
---
