---
apiVersion: v1
kind: Service
metadata:
  labels:
  name: murrayserver
spec:
  selector:
    app: murrayserver
  ports:
    - name: http
      port: 8080
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: murrayserver-pvc
spec:
  storageClassName: murray-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: murrayserver
  labels:
    app: murrayserver
spec:
  selector:
    matchLabels:
      app: murrayserver
  template:
    metadata:
      labels:
        app: murrayserver
    spec:
      containers:
        - name: murrayserver
          image: murrayserver
          imagePullPolicy: Never
          env:
            - name: MURRAYSERVER_LOG_PATH
              value: /data
          volumeMounts:
            - mountPath: "/data"
              name: storage
          resources:
            requests:
              cpu: "100m"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: murrayserver-pvc
---
